export const PROGRAM_LIST_REQUEST = 'PROGRAM_LIST_REQUEST'
export const PROGRAM_LIST_SUCCESS = 'PROGRAM_LIST_SUCCESS'
export const PROGRAM_LIST_FAIL = 'PROGRAM_LIST_FAIL'

export const PROGRAM_DELETE_REQUEST = 'PROGRAM_DELETE_REQUEST'
export const PROGRAM_DELETE_SUCCESS = 'PROGRAM_DELETE_SUCCESS'
export const PROGRAM_DELETE_FAIL = 'PROGRAM_DELETE_FAIL'

export const PROGRAM_ROUTINES_SUCCESS = 'PROGRAM_ROUTINES_SUCCESS'
export const PROGRAM_ROUTINES_FAIL = 'PROGRAM_ROUTINES_FAIL'
export const PROGRAM_ROUTINES_REQUEST = 'PROGRAM_ROUTINES_REQUEST'

export const ROUTINE_EXERCISES_SUCCESS = 'ROUTINE_EXERCISES_SUCCESS'
export const ROUTINE_EXERCISES_FAIL = 'ROUTINE_EXERCISES_FAIL'
export const ROUTINE_EXERCISES_REQUEST = 'ROUTINE_EXERCISES_REQUEST'

export const EXERCISE_PARAM_SUCCESS = 'EXERCISE_PARAM_SUCCESS'
export const EXERCISE_PARAM_FAIL = 'EXERCISE_PARAM_FAIL'
export const EXERCISE_PARAM_REQUEST = 'EXERCISE_PARAM_REQUEST'