export const PROGRAM_LIST_REQUEST = 'PROGRAM_LIST_REQUEST'
export const PROGRAM_LIST_SUCCESS = 'PROGRAM_LIST_SUCCESS'
export const PROGRAM_LIST_FAIL = 'PROGRAM_LIST_FAIL'

export const PROGRAM_ROUTINES_SUCCESS = 'PROGRAM_ROUTINES_SUCCESS'
export const PROGRAM_ROUTINES_FAIL = 'PROGRAM_ROUTINES_FAIL'
export const PROGRAM_ROUTINES_REQUEST = 'PROGRAM_ROUTINES_REQUEST'