# Generated by Django 4.0.1 on 2022-01-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_exercise_exerciseroutine_workoutparameters_routine_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutParameters',
            new_name='WorkoutParameter',
        ),
    ]
